name: Setup Database (Run Once)

on:
  workflow_dispatch: # Manual trigger only

jobs:
  setup-database:
    name: "Create Database"
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Get Database Connection Info
        run: |
          echo "Getting database connection details from SSM..."

          DB_HOST=$(aws ssm get-parameter --name "/main/rds_endpoint" --with-decryption --query "Parameter.Value" --output text)
          DB_USER=$(aws ssm get-parameter --name "/main/db_username" --with-decryption --query "Parameter.Value" --output text)
          DB_PASSWORD=$(aws ssm get-parameter --name "/main/db_password" --with-decryption --query "Parameter.Value" --output text)

          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_USER=$DB_USER" >> $GITHUB_ENV
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

          echo "✅ Connection details retrieved"
          echo "Host: $DB_HOST"
          echo "User: $DB_USER"

      - name: Test Connection
        run: |
          echo "Testing connection to PostgreSQL..."
          PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -d postgres -c "SELECT version();"

      - name: Create Database
        run: |
          echo "Creating customers_db database..."

          # Check if database exists
          DB_EXISTS=$(PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='customers_db'")

          if [ "$DB_EXISTS" = "1" ]; then
            echo "✅ Database 'customers_db' already exists"
          else
            echo "Creating database 'customers_db'..."
            PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -d postgres -c "CREATE DATABASE customers_db;"
            echo "✅ Database 'customers_db' created successfully"
          fi

      - name: Verify Database Creation
        run: |
          echo "Listing all databases:"
          PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -d postgres -c "\l"

          echo "✅ Database setup completed!"
